[tools]
flutter = "3.35.6"

[tasks.melos]
description = "Run melos using project's local version"
run = "dart run melos"

[tasks."melos:bootstrap"]
description = "Bootstrap melos workspace"
run = "dart run melos bootstrap"

[tasks."melos:clean"]
description = "Clean melos workspace"
run = "dart run melos clean"

[tasks."melos:run"]
description = "Run melos script"
run = "dart run melos run"